# Generated by Django 5.0.2 on 2024-03-24 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=2500)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('CLOSED', 'closed')], default='ACTIVE', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hiring_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_manager', to='employee.employee')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_role', to='employee.role')),
            ],
        ),
    ]
